### ISSUE TITLE
Dynamically set Authorization Header in getTokens Method

### ISSUE THREAD

**Issue by vellames2** [apinf/apinf-fiware#11]
On the line 126 of "fiware_server.js", it is necessary that the Authorization header be sent to get the access token.
The Authorization is maded by the combination of: **base64(client_id:secret)**
In the moment, the authorization header are static, we need to get the client_id and secret for configuration and generate the header dynamically

**Comment by midyan** [comment]
I fixed this issue on [this commit](https://github.com/apinf/apinf-fiware/pull/7/commits/02e36c7425a29b08abfed670ae125f0de82c08c1)

I'm getting the following error while trying to get the accessToken after retrieving the authentication code.
```
Error in OAuth Server: getTokens error. Failed to complete OAuth handshake with FIWARE IdM. failed [401] {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
```
And even though this error occurs, the login to FIWARE is successful. I have no idea of what might be causing this.

**Comment by vellames2** [comment]
@midyan can you send a pull request for review?
