### ISSUE TITLE
Write fiware-stub to mock HTTP requests during unit testing

### ISSUE THREAD

**Issue by midyan** [apinf/apinf-fiware#14]
The node-nock is not playing very well to mock the HTTP requests during the authentication flow (popup/redirect).

It will be better to write a customized stub from scratch. [This](https://github.com/xolvio/meteor-github-stub) example is exactly what needs to be done.

@mauriciovieira and @Vellames what do you think?

## Useful links

* [How to write tests](https://forums.meteor.com/t/client-testing-how-to-write-tests-with-a-logged-in-oauth-user/4674/4)

**Comment by mauriciovieira** [comment]
Is this part or separate from #5 ?

**Comment by midyan** [comment]
Part of #5. Should I edit that issue with this task?

**Comment by mauriciovieira** [comment]
Yes. It's in the same scope and will be closed by the same pull request. So, feel free to add the contents there and close this one.

**Comment by midyan** [comment]
Closed by #7
