### ISSUE TITLE
Parameterize server configuration

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/apinf-fiware#2]
Given that the oauth authentication is working for [FIWARE LAB](https://account.lab.fiware.org/), the next step is to allow the server configuration to be specified on, either:

- a settings file
- dynamically on runtime by the meteor application that installs this package.

**Comment by vellames2** [comment]
@mauriciovieira  I think that the rootURL in configuration solve this problem, right?

**Comment by mauriciovieira** [comment]
@Vellames Yes. So I will change the scope of this task.

**Comment by mauriciovieira** [comment]
@Vellames You are right.
