### ISSUE TITLE
Package not works

### ISSUE THREAD

**Issue by vellames2** [apinf/apinf-fiware#8]
The package presents some problems with the integration with OAuth2 server of fiware:
The problems are:

- Error trying to get the authorization code 
- Error trying to get the access token 
- Error trying to get the basic informations of user (getAccounts)

**Comment by mauriciovieira** [comment]
@Vellames which problems? Can you be more descriptive on this issue?

**Comment by vellames2** [comment]
@mauriciovieira updated
